CREATE DATABASE  IF NOT EXISTS router;
USE router;

--@block
CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT,
userName VARCHAR(50)  NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password  VARCHAR(50) NOT NULL
);


